# Generated by Django 4.2.7 on 2025-10-13 04:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Tweet content (max 280 characters)",
                        max_length=280,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                280, "Tweet content cannot exceed 280 characters"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The user who created this tweet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_tweet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent tweet if this is a reply",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="tweets.tweet",
                    ),
                ),
            ],
            options={
                "db_table": "tweets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["author", "-created_at"],
                        name="tweets_author__0f055d_idx",
                    ),
                    models.Index(
                        fields=["parent_tweet"], name="tweets_parent__753f47_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="tweets_created_d942a6_idx"
                    ),
                    models.Index(
                        fields=["is_deleted"], name="tweets_is_dele_9644b3_idx"
                    ),
                ],
            },
        ),
    ]
