# Generated by Django 4.2.7 on 2025-10-13 05:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gif", "GIF"),
                        ],
                        help_text="Type of media file",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Media file (image or video)",
                        upload_to="tweet_media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "webm",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text for accessibility",
                        max_length=420,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Media width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Media height in pixels", null=True
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tweet",
                    models.ForeignKey(
                        help_text="The tweet this media belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="tweets.tweet",
                    ),
                ),
            ],
            options={
                "db_table": "tweet_media",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["tweet"], name="tweet_media_tweet_i_1828c7_idx"
                    ),
                    models.Index(
                        fields=["media_type"], name="tweet_media_media_t_a21d5e_idx"
                    ),
                ],
            },
        ),
    ]
