# Generated by Django 4.2.7 on 2025-10-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Hashtag name without the # symbol",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this hashtag has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hashtags",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="TweetHashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Position of hashtag in tweet content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hashtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweet_hashtags",
                        to="tweets.hashtag",
                    ),
                ),
                (
                    "tweet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweet_hashtags",
                        to="tweets.tweet",
                    ),
                ),
            ],
            options={
                "db_table": "tweet_hashtags",
            },
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(fields=["name"], name="hashtags_name_33a019_idx"),
        ),
        migrations.AddIndex(
            model_name="hashtag",
            index=models.Index(
                fields=["-usage_count"], name="hashtags_usage_c_775a07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tweethashtag",
            index=models.Index(fields=["tweet"], name="tweet_hasht_tweet_i_8fc22f_idx"),
        ),
        migrations.AddIndex(
            model_name="tweethashtag",
            index=models.Index(
                fields=["hashtag"], name="tweet_hasht_hashtag_0c4249_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tweethashtag",
            unique_together={("tweet", "hashtag")},
        ),
    ]
