# Generated by Django 4.2.7 on 2025-10-13 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_permission_role_communitymember_custom_role_and_more"),
        ("tweets", "0003_hashtag_tweethashtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="community",
            field=models.ForeignKey(
                blank=True,
                help_text="Community this tweet belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets",
                to="communities.community",
            ),
        ),
    ]
