# Generated by Django 4.2.7 on 2025-10-13 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Permission name", max_length=50, unique=True
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Permission codename for programmatic use",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Permission description", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "communities_permission",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Role name", max_length=50, unique=True),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Role codename for programmatic use",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Role description", null=True
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Whether this is a default system role"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions assigned to this role",
                        related_name="roles",
                        to="communities.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "communities_role",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="communitymember",
            name="custom_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Custom role with specific permissions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="communities.role",
            ),
        ),
        migrations.CreateModel(
            name="CommunityRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_roles",
                        to="communities.community",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_assignments",
                        to="communities.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Role",
                "verbose_name_plural": "Community Roles",
                "db_table": "communities_communityrole",
                "unique_together": {("community", "role")},
            },
        ),
    ]
