# Generated by Django 4.2.7 on 2025-10-13 05:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the list",
                        max_length=100,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                100, "List name cannot exceed 100 characters"
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the list",
                        max_length=500,
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                500, "List description cannot exceed 500 characters"
                            )
                        ],
                    ),
                ),
                (
                    "privacy",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        help_text="Privacy setting for the list",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who created and owns this list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this membership is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "list",
                    models.ForeignKey(
                        help_text="The list this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="lists.list",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is a member of the list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "list_members",
                "indexes": [
                    models.Index(
                        fields=["list", "is_active"],
                        name="list_member_list_id_eaf89e_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="list_member_user_id_8f176b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="list_member_created_9e3e8b_idx"
                    ),
                ],
                "unique_together": {("list", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(
                fields=["owner", "-created_at"], name="lists_owner_i_fb47e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["privacy"], name="lists_privacy_5ec5a3_idx"),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["is_deleted"], name="lists_is_dele_8bd017_idx"),
        ),
        migrations.AddIndex(
            model_name="list",
            index=models.Index(fields=["name"], name="lists_name_cc7c76_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("owner", "name")},
        ),
    ]
