# Generated by Django 4.2.7 on 2025-10-13 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the reported object"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("hate_speech", "Hate Speech"),
                            ("violence", "Violence"),
                            ("inappropriate_content", "Inappropriate Content"),
                            ("copyright", "Copyright Violation"),
                            ("fake_news", "Fake News"),
                            ("impersonation", "Impersonation"),
                            ("other", "Other"),
                        ],
                        help_text="Type of violation being reported",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the report",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        help_text="Current status of the report",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from moderator about resolution",
                        null=True,
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was resolved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_moderator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator assigned to review this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of content being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="User who submitted the report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moderator who resolved the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reporter"], name="reports_reporte_5cbb43_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="reports_content_0cd725_idx",
                    ),
                    models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
                    models.Index(
                        fields=["report_type"], name="reports_report__ff8b25_idx"
                    ),
                    models.Index(
                        fields=["assigned_moderator"], name="reports_assigne_3f75d0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_created_c5f642_idx"
                    ),
                ],
                "unique_together": {("reporter", "content_type", "object_id")},
            },
        ),
    ]
