# Generated by Django 4.2.7 on 2025-10-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("no_action", "No Action Required"),
                            ("warning_issued", "Warning Issued"),
                            ("content_removed", "Content Removed"),
                            ("account_suspended", "Account Suspended"),
                            ("account_banned", "Account Banned"),
                            ("content_flagged", "Content Flagged"),
                            ("escalated", "Escalated to Higher Authority"),
                            ("other", "Other Action"),
                        ],
                        help_text="Type of moderation action taken",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the action taken"
                    ),
                ),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this action was taken automatically",
                    ),
                ),
                (
                    "severity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Medium"),
                            (3, "High"),
                            (4, "Critical"),
                        ],
                        default=1,
                        help_text="Severity level of the action",
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data related to the action",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        help_text="Moderator who took this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Report this action is related to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="moderation.report",
                    ),
                ),
            ],
            options={
                "db_table": "moderation_actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report"], name="moderation__report__31051b_idx"
                    ),
                    models.Index(
                        fields=["moderator"], name="moderation__moderat_b5120b_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="moderation__action__4ba523_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="moderation__created_05f00e_idx"
                    ),
                    models.Index(
                        fields=["severity_level"], name="moderation__severit_b59a6b_idx"
                    ),
                ],
            },
        ),
    ]
