# Generated by Django 4.2.7 on 2025-10-13 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tweets", "0003_hashtag_tweethashtag_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Retweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweet",
                    models.ForeignKey(
                        help_text="The tweet that was retweeted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retweets",
                        to="tweets.tweet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who retweeted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retweets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "retweets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="retweets_user_id_059969_idx"),
                    models.Index(fields=["tweet"], name="retweets_tweet_i_21b66d_idx"),
                    models.Index(
                        fields=["created_at"], name="retweets_created_3e7200_idx"
                    ),
                ],
                "unique_together": {("user", "tweet")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweet",
                    models.ForeignKey(
                        help_text="The tweet that was liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="tweets.tweet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who liked the tweet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="likes_user_id_4c8dad_idx"),
                    models.Index(fields=["tweet"], name="likes_tweet_i_b3942a_idx"),
                    models.Index(
                        fields=["created_at"], name="likes_created_6ac82b_idx"
                    ),
                ],
                "unique_together": {("user", "tweet")},
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="The user who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        help_text="The user being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "follows",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["follower"], name="follows_followe_ca9b09_idx"
                    ),
                    models.Index(
                        fields=["following"], name="follows_followi_dcb467_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="follows_created_95ec29_idx"
                    ),
                ],
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweet",
                    models.ForeignKey(
                        help_text="The tweet that was bookmarked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="tweets.tweet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who bookmarked the tweet",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bookmarks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="bookmarks_user_id_687ca2_idx"),
                    models.Index(fields=["tweet"], name="bookmarks_tweet_i_d069ad_idx"),
                    models.Index(
                        fields=["created_at"], name="bookmarks_created_01023a_idx"
                    ),
                ],
                "unique_together": {("user", "tweet")},
            },
        ),
    ]
